CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP VIEW IF EXISTS user_badge_overview CASCADE;
DROP VIEW IF EXISTS exercise_usage_stats CASCADE;
DROP VIEW IF EXISTS weekly_muscle_group_summary CASCADE;
DROP VIEW IF EXISTS user_training_summary CASCADE;
DROP VIEW IF EXISTS admin_user_overview CASCADE;

DROP TABLE IF EXISTS user_badges CASCADE;
DROP TABLE IF EXISTS badges CASCADE;
DROP TABLE IF EXISTS performed_sets CASCADE;
DROP TABLE IF EXISTS workout_sessions CASCADE;
DROP TABLE IF EXISTS user_workout_plans CASCADE;
DROP TABLE IF EXISTS workout_plan_exercises CASCADE;
DROP TABLE IF EXISTS workout_plan_days CASCADE;
DROP TABLE IF EXISTS workout_plans CASCADE;
DROP TABLE IF EXISTS exercise_muscle_groups CASCADE;
DROP TABLE IF EXISTS exercises CASCADE;
DROP TABLE IF EXISTS equipment CASCADE;
DROP TABLE IF EXISTS muscle_groups CASCADE;
DROP TABLE IF EXISTS user_profiles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

CREATE TABLE roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    blocked_at TIMESTAMP WITH TIME ZONE,
    blocked_reason TEXT,
    last_login_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX users_email_lower_idx ON users (LOWER(email));

CREATE TABLE user_profiles (
    user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    bio TEXT,
    birth_date DATE,
    height_cm NUMERIC(5,2) CHECK (height_cm IS NULL OR height_cm > 0),
    body_weight_kg NUMERIC(5,2) CHECK (body_weight_kg IS NULL OR body_weight_kg > 0),
    experience_level VARCHAR(20) NOT NULL DEFAULT 'beginner'
        CHECK (experience_level IN ('beginner', 'intermediate', 'advanced')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE muscle_groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE equipment (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE exercises (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id INTEGER REFERENCES equipment(id) ON DELETE SET NULL,
    name VARCHAR(120) NOT NULL UNIQUE,
    slug VARCHAR(140) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    technique_notes TEXT,
    difficulty VARCHAR(20) NOT NULL DEFAULT 'beginner'
        CHECK (difficulty IN ('beginner', 'intermediate', 'advanced')),
    video_url TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE exercise_muscle_groups (
    exercise_id INTEGER NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
    muscle_group_id INTEGER NOT NULL REFERENCES muscle_groups(id) ON DELETE RESTRICT,
    involvement VARCHAR(20) NOT NULL DEFAULT 'primary'
        CHECK (involvement IN ('primary', 'secondary', 'stabilizer')),
    PRIMARY KEY (exercise_id, muscle_group_id)
);

CREATE TABLE workout_plans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    name VARCHAR(140) NOT NULL,
    description TEXT,
    goal VARCHAR(40) NOT NULL DEFAULT 'hypertrophy'
        CHECK (goal IN ('strength', 'hypertrophy', 'endurance', 'general')),
    level VARCHAR(20) NOT NULL DEFAULT 'beginner'
        CHECK (level IN ('beginner', 'intermediate', 'advanced')),
    is_template BOOLEAN NOT NULL DEFAULT FALSE,
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE workout_plan_days (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_plan_id INTEGER NOT NULL REFERENCES workout_plans(id) ON DELETE CASCADE,
    name VARCHAR(120) NOT NULL,
    day_of_week SMALLINT CHECK (day_of_week BETWEEN 1 AND 7),
    day_order INTEGER NOT NULL CHECK (day_order > 0),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (workout_plan_id, day_order)
);

CREATE TABLE workout_plan_exercises (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_plan_day_id INTEGER NOT NULL REFERENCES workout_plan_days(id) ON DELETE CASCADE,
    exercise_id INTEGER NOT NULL REFERENCES exercises(id) ON DELETE RESTRICT,
    exercise_order INTEGER NOT NULL CHECK (exercise_order > 0),
    target_sets INTEGER NOT NULL CHECK (target_sets > 0),
    target_reps_min INTEGER CHECK (target_reps_min IS NULL OR target_reps_min > 0),
    target_reps_max INTEGER CHECK (target_reps_max IS NULL OR target_reps_max > 0),
    target_rpe NUMERIC(3,1) CHECK (target_rpe IS NULL OR target_rpe BETWEEN 0 AND 10),
    rest_seconds INTEGER NOT NULL DEFAULT 90 CHECK (rest_seconds > 0),
    notes TEXT,
    UNIQUE (workout_plan_day_id, exercise_order),
    CHECK (
        target_reps_min IS NULL
        OR target_reps_max IS NULL
        OR target_reps_min <= target_reps_max
    )
);

CREATE TABLE user_workout_plans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    workout_plan_id INTEGER NOT NULL REFERENCES workout_plans(id) ON DELETE CASCADE,
    custom_name VARCHAR(140),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    assigned_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, workout_plan_id)
);

CREATE TABLE workout_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    workout_plan_id INTEGER REFERENCES workout_plans(id) ON DELETE SET NULL,
    workout_plan_day_id INTEGER REFERENCES workout_plan_days(id) ON DELETE SET NULL,
    name VARCHAR(140) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'planned'
        CHECK (status IN ('planned', 'in_progress', 'finished', 'cancelled')),
    started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP WITH TIME ZONE,
    session_rpe NUMERIC(3,1) CHECK (session_rpe IS NULL OR session_rpe BETWEEN 0 AND 10),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (finished_at IS NULL OR finished_at >= started_at)
);

CREATE TABLE performed_sets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_session_id INTEGER NOT NULL REFERENCES workout_sessions(id) ON DELETE CASCADE,
    exercise_id INTEGER NOT NULL REFERENCES exercises(id) ON DELETE RESTRICT,
    set_order INTEGER NOT NULL CHECK (set_order > 0),
    set_type VARCHAR(20) NOT NULL DEFAULT 'working'
        CHECK (set_type IN ('warmup', 'working', 'drop', 'failure')),
    weight_kg NUMERIC(7,2) NOT NULL DEFAULT 0 CHECK (weight_kg >= 0),
    reps INTEGER NOT NULL CHECK (reps > 0),
    rpe NUMERIC(3,1) CHECK (rpe IS NULL OR rpe BETWEEN 0 AND 10),
    note TEXT,
    performed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (workout_session_id, exercise_id, set_order)
);

CREATE TABLE badges (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    exercise_id INTEGER REFERENCES exercises(id) ON DELETE SET NULL,
    muscle_group_id INTEGER REFERENCES muscle_groups(id) ON DELETE SET NULL,
    name VARCHAR(120) NOT NULL UNIQUE,
    slug VARCHAR(140) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    icon VARCHAR(60) NOT NULL DEFAULT 'military_tech',
    criteria_type VARCHAR(40) NOT NULL
        CHECK (criteria_type IN ('exercise_weight', 'total_sessions', 'total_volume', 'muscle_sets', 'custom')),
    target_value NUMERIC(10,2) NOT NULL CHECK (target_value > 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_badges (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    badge_id INTEGER NOT NULL REFERENCES badges(id) ON DELETE CASCADE,
    source_workout_session_id INTEGER REFERENCES workout_sessions(id) ON DELETE SET NULL,
    current_value NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (current_value >= 0),
    awarded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, badge_id)
);

CREATE INDEX users_role_id_idx ON users(role_id);
CREATE INDEX exercises_equipment_id_idx ON exercises(equipment_id);
CREATE INDEX exercise_muscle_groups_muscle_group_id_idx ON exercise_muscle_groups(muscle_group_id);
CREATE INDEX workout_plans_owner_user_id_idx ON workout_plans(owner_user_id);
CREATE INDEX workout_plan_days_plan_id_idx ON workout_plan_days(workout_plan_id);
CREATE INDEX workout_plan_exercises_day_id_idx ON workout_plan_exercises(workout_plan_day_id);
CREATE INDEX user_workout_plans_user_id_idx ON user_workout_plans(user_id);
CREATE INDEX workout_sessions_user_id_idx ON workout_sessions(user_id);
CREATE INDEX workout_sessions_started_at_idx ON workout_sessions(started_at);
CREATE INDEX performed_sets_session_id_idx ON performed_sets(workout_session_id);
CREATE INDEX performed_sets_exercise_id_idx ON performed_sets(exercise_id);
CREATE INDEX badges_created_by_user_id_idx ON badges(created_by_user_id);
CREATE INDEX badges_exercise_id_idx ON badges(exercise_id);
CREATE INDEX badges_muscle_group_id_idx ON badges(muscle_group_id);
CREATE INDEX user_badges_user_id_idx ON user_badges(user_id);
CREATE INDEX user_badges_badge_id_idx ON user_badges(badge_id);

CREATE OR REPLACE FUNCTION touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER users_touch_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER user_profiles_touch_updated_at
BEFORE UPDATE ON user_profiles
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER exercises_touch_updated_at
BEFORE UPDATE ON exercises
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER workout_plans_touch_updated_at
BEFORE UPDATE ON workout_plans
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER workout_plan_days_touch_updated_at
BEFORE UPDATE ON workout_plan_days
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER user_workout_plans_touch_updated_at
BEFORE UPDATE ON user_workout_plans
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER workout_sessions_touch_updated_at
BEFORE UPDATE ON workout_sessions
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER badges_touch_updated_at
BEFORE UPDATE ON badges
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE OR REPLACE FUNCTION calculate_session_volume(p_session_id INTEGER)
RETURNS NUMERIC(12,2) AS $$
    SELECT COALESCE(SUM(weight_kg * reps), 0)::NUMERIC(12,2)
    FROM performed_sets
    WHERE workout_session_id = p_session_id;
$$ LANGUAGE SQL STABLE;

CREATE OR REPLACE FUNCTION award_exercise_weight_badges()
RETURNS TRIGGER AS $$
DECLARE
    session_user_id INTEGER;
BEGIN
    SELECT user_id INTO session_user_id
    FROM workout_sessions
    WHERE id = NEW.workout_session_id;

    INSERT INTO user_badges (user_id, badge_id, source_workout_session_id, current_value)
    SELECT
        session_user_id,
        b.id,
        NEW.workout_session_id,
        NEW.weight_kg
    FROM badges b
    WHERE b.is_active = TRUE
      AND b.criteria_type = 'exercise_weight'
      AND b.exercise_id = NEW.exercise_id
      AND NEW.weight_kg >= b.target_value
    ON CONFLICT (user_id, badge_id) DO UPDATE
    SET current_value = GREATEST(user_badges.current_value, EXCLUDED.current_value);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER performed_sets_award_exercise_weight_badges
AFTER INSERT ON performed_sets
FOR EACH ROW EXECUTE FUNCTION award_exercise_weight_badges();

CREATE VIEW admin_user_overview AS
SELECT
    u.id,
    u.username,
    u.email,
    r.name AS role,
    u.is_active,
    u.blocked_at,
    u.created_at,
    p.firstname,
    p.lastname,
    COUNT(DISTINCT ws.id) FILTER (WHERE ws.status = 'finished') AS finished_workouts
FROM users u
JOIN roles r ON r.id = u.role_id
LEFT JOIN user_profiles p ON p.user_id = u.id
LEFT JOIN workout_sessions ws ON ws.user_id = u.id
GROUP BY u.id, r.name, p.firstname, p.lastname;

CREATE VIEW user_training_summary AS
SELECT
    u.id AS user_id,
    u.username,
    COUNT(DISTINCT ws.id) FILTER (WHERE ws.status = 'finished') AS finished_sessions,
    COALESCE(SUM(ps.weight_kg * ps.reps), 0)::NUMERIC(12,2) AS total_volume_kg,
    COUNT(ps.id) AS total_sets,
    ROUND(AVG(ps.rpe), 2) AS average_set_rpe,
    MAX(ws.started_at) FILTER (WHERE ws.status = 'finished') AS last_workout_at
FROM users u
LEFT JOIN workout_sessions ws ON ws.user_id = u.id
LEFT JOIN performed_sets ps ON ps.workout_session_id = ws.id
GROUP BY u.id, u.username;

CREATE VIEW weekly_muscle_group_summary AS
SELECT
    u.id AS user_id,
    u.username,
    DATE_TRUNC('week', ws.started_at)::DATE AS week_start,
    mg.id AS muscle_group_id,
    mg.name AS muscle_group,
    COUNT(ps.id) AS sets_count,
    COALESCE(SUM(ps.weight_kg * ps.reps), 0)::NUMERIC(12,2) AS volume_kg,
    ROUND(AVG(ps.rpe), 2) AS average_rpe
FROM users u
JOIN workout_sessions ws ON ws.user_id = u.id
JOIN performed_sets ps ON ps.workout_session_id = ws.id
JOIN exercises e ON e.id = ps.exercise_id
JOIN exercise_muscle_groups emg ON emg.exercise_id = e.id AND emg.involvement = 'primary'
JOIN muscle_groups mg ON mg.id = emg.muscle_group_id
WHERE ws.status = 'finished'
GROUP BY u.id, u.username, DATE_TRUNC('week', ws.started_at)::DATE, mg.id, mg.name;

CREATE VIEW exercise_usage_stats AS
WITH plan_usage AS (
    SELECT
        exercise_id,
        COUNT(*) AS planned_occurrences
    FROM workout_plan_exercises
    GROUP BY exercise_id
),
set_usage AS (
    SELECT
        exercise_id,
        COUNT(DISTINCT workout_session_id) AS sessions_used,
        COUNT(*) AS performed_sets,
        COALESCE(SUM(weight_kg * reps), 0)::NUMERIC(12,2) AS total_volume_kg,
        MAX(weight_kg) AS max_weight_kg
    FROM performed_sets
    GROUP BY exercise_id
)
SELECT
    e.id AS exercise_id,
    e.name AS exercise_name,
    eq.name AS equipment,
    COALESCE(pu.planned_occurrences, 0) AS planned_occurrences,
    COALESCE(su.sessions_used, 0) AS sessions_used,
    COALESCE(su.performed_sets, 0) AS performed_sets,
    COALESCE(su.total_volume_kg, 0)::NUMERIC(12,2) AS total_volume_kg,
    su.max_weight_kg
FROM exercises e
LEFT JOIN equipment eq ON eq.id = e.equipment_id
LEFT JOIN plan_usage pu ON pu.exercise_id = e.id
LEFT JOIN set_usage su ON su.exercise_id = e.id;

CREATE VIEW user_badge_overview AS
SELECT
    u.id AS user_id,
    u.username,
    b.id AS badge_id,
    b.name AS badge_name,
    b.criteria_type,
    b.target_value,
    ub.current_value,
    ub.awarded_at,
    ws.name AS source_session
FROM user_badges ub
JOIN users u ON u.id = ub.user_id
JOIN badges b ON b.id = ub.badge_id
LEFT JOIN workout_sessions ws ON ws.id = ub.source_workout_session_id;

INSERT INTO roles (name, description) VALUES
    ('admin', 'Administrator aplikacji z dostępem do zarządzania użytkownikami.'),
    ('user', 'Standardowy użytkownik prowadzący dziennik treningowy.');

INSERT INTO users (role_id, username, email, password, is_active) VALUES
    ((SELECT id FROM roles WHERE name = 'admin'), 'admin', 'admin@hipertrof.io', crypt('admin123', gen_salt('bf')), TRUE),
    ((SELECT id FROM roles WHERE name = 'user'), 'user', 'user@wdpai.com', crypt('wdpai123', gen_salt('bf')), TRUE),
    ((SELECT id FROM roles WHERE name = 'user'), 'blocked_user', 'blocked@wdpai.com', crypt('wdpai123', gen_salt('bf')), FALSE);

UPDATE users
SET blocked_at = CURRENT_TIMESTAMP, blocked_reason = 'Konto testowo zablokowane przez administratora.'
WHERE username = 'blocked_user';

INSERT INTO user_profiles (user_id, firstname, lastname, bio, height_cm, body_weight_kg, experience_level) VALUES
    ((SELECT id FROM users WHERE username = 'admin'), 'Admin', 'Systemowy', 'Konto administracyjne do testowania panelu.', NULL, NULL, 'advanced'),
    ((SELECT id FROM users WHERE username = 'user'), 'Jan', 'Trenujący', 'Trening hipertroficzny 4 razy w tygodniu.', 181, 84.50, 'intermediate'),
    ((SELECT id FROM users WHERE username = 'blocked_user'), 'Jan', 'Zablokowany', 'Konto do sprawdzania blokady logowania.', 176, 79.00, 'beginner');

INSERT INTO muscle_groups (name, description) VALUES
    ('Klatka piersiowa', 'Mięśnie piersiowe większe i mniejsze.'),
    ('Plecy', 'Najszerszy grzbietu, czworoboczne i mięśnie środka pleców.'),
    ('Barki', 'Przedni, boczny i tylny akton mięśnia naramiennego.'),
    ('Biceps', 'Mięsień dwugłowy ramienia.'),
    ('Triceps', 'Mięsień trójgłowy ramienia.'),
    ('Czworogłowe uda', 'Przednia część uda.'),
    ('Dwugłowe uda', 'Tylna część uda.'),
    ('Pośladki', 'Mięśnie pośladkowe.'),
    ('Łydki', 'Mięśnie podudzia.'),
    ('Core', 'Mięśnie brzucha i stabilizacja tułowia.');

INSERT INTO equipment (name) VALUES
    ('Sztanga'),
    ('Hantle'),
    ('Maszyna'),
    ('Wyciąg'),
    ('Masa ciała'),
    ('Ławka'),
    ('Kettlebell');

INSERT INTO exercises (equipment_id, name, slug, description, technique_notes, difficulty, video_url) VALUES
    ((SELECT id FROM equipment WHERE name = 'Sztanga'), 'Wyciskanie sztangi leżąc', 'wyciskanie-sztangi-lezac', 'Podstawowe ćwiczenie na klatkę piersiową wykonywane na ławce poziomej.', 'Utrzymuj łopatki ściągnięte, kontroluj tor sztangi i nie odrywaj pośladków od ławki.', 'intermediate', NULL),
    ((SELECT id FROM equipment WHERE name = 'Hantle'), 'Wyciskanie hantli na skosie dodatnim', 'wyciskanie-hantli-skos-dodatni', 'Ćwiczenie akcentujące górną część klatki piersiowej.', 'Prowadź hantle stabilnie i nie skracaj zakresu ruchu.', 'intermediate', NULL),
    ((SELECT id FROM equipment WHERE name = 'Masa ciała'), 'Pompki', 'pompki', 'Wielostawowe ćwiczenie z masą ciała na klatkę i triceps.', 'Trzymaj ciało w jednej linii i kontroluj zejście.', 'beginner', NULL),
    ((SELECT id FROM equipment WHERE name = 'Sztanga'), 'Wyciskanie żołnierskie', 'wyciskanie-zolnierskie', 'Wyciskanie sztangi nad głowę rozwijające barki i stabilizację.', 'Nie wyginaj nadmiernie odcinka lędźwiowego.', 'intermediate', NULL),
    ((SELECT id FROM equipment WHERE name = 'Hantle'), 'Unoszenie hantli bokiem', 'unoszenie-hantli-bokiem', 'Izolowane ćwiczenie na boczny akton barków.', 'Prowadź łokcie lekko ugięte i unikaj szarpania.', 'beginner', NULL),
    ((SELECT id FROM equipment WHERE name = 'Masa ciała'), 'Podciąganie nachwytem', 'podciaganie-nachwytem', 'Ćwiczenie na plecy i biceps wykonywane na drążku.', 'Rozpoczynaj z pełnego zwisu i prowadź klatkę do drążka.', 'intermediate', NULL),
    ((SELECT id FROM equipment WHERE name = 'Sztanga'), 'Wiosłowanie sztangą', 'wioslowanie-sztanga', 'Wielostawowe ćwiczenie na grubość pleców.', 'Utrzymuj neutralne plecy i prowadź sztangę w stronę bioder.', 'intermediate', NULL),
    ((SELECT id FROM equipment WHERE name = 'Wyciąg'), 'Ściąganie drążka do klatki', 'sciaganie-drazka-do-klatki', 'Maszynowa alternatywa dla podciągania.', 'Ściągaj łopatki i nie bujaj tułowiem.', 'beginner', NULL),
    ((SELECT id FROM equipment WHERE name = 'Wyciąg'), 'Wiosłowanie siedząc na wyciągu', 'wioslowanie-siedzac-wyciag', 'Ćwiczenie na środek pleców z linką wyciągu.', 'Zatrzymaj ruch na moment przy tułowiu.', 'beginner', NULL),
    ((SELECT id FROM equipment WHERE name = 'Sztanga'), 'Przysiad ze sztangą', 'przysiad-ze-sztanga', 'Podstawowe ćwiczenie na nogi i pośladki.', 'Utrzymuj napięty brzuch, kolana prowadź zgodnie z linią stóp.', 'intermediate', NULL),
    ((SELECT id FROM equipment WHERE name = 'Sztanga'), 'Martwy ciąg rumuński', 'martwy-ciag-rumunski', 'Ćwiczenie na tylną taśmę uda i pośladki.', 'Cofaj biodra, zachowaj neutralne plecy i czuj rozciągnięcie dwugłowych.', 'intermediate', NULL),
    ((SELECT id FROM equipment WHERE name = 'Maszyna'), 'Wypychanie na suwnicy', 'wypychanie-na-suwnicy', 'Ćwiczenie maszynowe na uda i pośladki.', 'Nie blokuj agresywnie kolan w górze ruchu.', 'beginner', NULL),
    ((SELECT id FROM equipment WHERE name = 'Hantle'), 'Wykroki z hantlami', 'wykroki-z-hantlami', 'Ćwiczenie unilateralne na nogi i pośladki.', 'Kontroluj krok i utrzymuj stabilne kolano.', 'beginner', NULL),
    ((SELECT id FROM equipment WHERE name = 'Maszyna'), 'Uginanie nóg leżąc', 'uginanie-nog-lezac', 'Izolowane ćwiczenie na tył uda.', 'Nie odrywaj bioder od podparcia.', 'beginner', NULL),
    ((SELECT id FROM equipment WHERE name = 'Maszyna'), 'Wspięcia na palce', 'wspiecia-na-palce', 'Ćwiczenie na mięśnie łydek.', 'Zatrzymaj ruch na górze i kontroluj zejście.', 'beginner', NULL),
    ((SELECT id FROM equipment WHERE name = 'Sztanga'), 'Martwy ciąg klasyczny', 'martwy-ciag-klasyczny', 'Ciężkie ćwiczenie wielostawowe angażujące całe ciało.', 'Napnij brzuch przed oderwaniem sztangi i utrzymuj ją blisko ciała.', 'advanced', NULL),
    ((SELECT id FROM equipment WHERE name = 'Sztanga'), 'Hip thrust', 'hip-thrust', 'Ćwiczenie ukierunkowane na pośladki.', 'Zatrzymaj biodra w pełnym wyproście bez przeprostu lędźwi.', 'beginner', NULL),
    ((SELECT id FROM equipment WHERE name = 'Hantle'), 'Uginanie ramion z hantlami', 'uginanie-ramion-z-hantlami', 'Podstawowe ćwiczenie na biceps.', 'Nie bujaj tułowiem i kontroluj opuszczanie.', 'beginner', NULL),
    ((SELECT id FROM equipment WHERE name = 'Hantle'), 'Uginanie młotkowe', 'uginanie-mlotkowe', 'Wariant uginania ramion mocniej angażujący ramienny.', 'Trzymaj neutralny chwyt przez cały ruch.', 'beginner', NULL),
    ((SELECT id FROM equipment WHERE name = 'Wyciąg'), 'Prostowanie ramion na wyciągu', 'prostowanie-ramion-na-wyciagu', 'Izolowane ćwiczenie na triceps.', 'Łokcie trzymaj blisko tułowia.', 'beginner', NULL),
    ((SELECT id FROM equipment WHERE name = 'Sztanga'), 'Francuskie wyciskanie leżąc', 'francuskie-wyciskanie-lezac', 'Ćwiczenie izolujące triceps.', 'Kontroluj łokcie i nie opuszczaj ciężaru zbyt gwałtownie.', 'intermediate', NULL),
    ((SELECT id FROM equipment WHERE name = 'Masa ciała'), 'Plank', 'plank', 'Ćwiczenie izometryczne na stabilizację tułowia.', 'Nie opuszczaj bioder i utrzymuj napięcie brzucha.', 'beginner', NULL),
    ((SELECT id FROM equipment WHERE name = 'Wyciąg'), 'Spięcia brzucha na wyciągu', 'spiecia-brzucha-na-wyciagu', 'Ćwiczenie na mięśnie brzucha z obciążeniem.', 'Zwijaj tułów, nie ciągnij rękami.', 'beginner', NULL),
    ((SELECT id FROM equipment WHERE name = 'Wyciąg'), 'Face pull', 'face-pull', 'Ćwiczenie na tylny akton barków i zdrowie obręczy barkowej.', 'Prowadź linkę do twarzy i rotuj ramiona na zewnątrz.', 'beginner', NULL),
    ((SELECT id FROM equipment WHERE name = 'Masa ciała'), 'Dipy na poręczach', 'dipy-na-poreczach', 'Ćwiczenie na triceps i dolną część klatki.', 'Kontroluj głębokość i nie zapadaj barków.', 'intermediate', NULL);

INSERT INTO exercise_muscle_groups (exercise_id, muscle_group_id, involvement) VALUES
    ((SELECT id FROM exercises WHERE slug = 'wyciskanie-sztangi-lezac'), (SELECT id FROM muscle_groups WHERE name = 'Klatka piersiowa'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'wyciskanie-sztangi-lezac'), (SELECT id FROM muscle_groups WHERE name = 'Triceps'), 'secondary'),
    ((SELECT id FROM exercises WHERE slug = 'wyciskanie-sztangi-lezac'), (SELECT id FROM muscle_groups WHERE name = 'Barki'), 'secondary'),
    ((SELECT id FROM exercises WHERE slug = 'wyciskanie-hantli-skos-dodatni'), (SELECT id FROM muscle_groups WHERE name = 'Klatka piersiowa'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'wyciskanie-hantli-skos-dodatni'), (SELECT id FROM muscle_groups WHERE name = 'Barki'), 'secondary'),
    ((SELECT id FROM exercises WHERE slug = 'pompki'), (SELECT id FROM muscle_groups WHERE name = 'Klatka piersiowa'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'pompki'), (SELECT id FROM muscle_groups WHERE name = 'Triceps'), 'secondary'),
    ((SELECT id FROM exercises WHERE slug = 'wyciskanie-zolnierskie'), (SELECT id FROM muscle_groups WHERE name = 'Barki'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'wyciskanie-zolnierskie'), (SELECT id FROM muscle_groups WHERE name = 'Triceps'), 'secondary'),
    ((SELECT id FROM exercises WHERE slug = 'unoszenie-hantli-bokiem'), (SELECT id FROM muscle_groups WHERE name = 'Barki'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'podciaganie-nachwytem'), (SELECT id FROM muscle_groups WHERE name = 'Plecy'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'podciaganie-nachwytem'), (SELECT id FROM muscle_groups WHERE name = 'Biceps'), 'secondary'),
    ((SELECT id FROM exercises WHERE slug = 'wioslowanie-sztanga'), (SELECT id FROM muscle_groups WHERE name = 'Plecy'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'wioslowanie-sztanga'), (SELECT id FROM muscle_groups WHERE name = 'Biceps'), 'secondary'),
    ((SELECT id FROM exercises WHERE slug = 'sciaganie-drazka-do-klatki'), (SELECT id FROM muscle_groups WHERE name = 'Plecy'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'sciaganie-drazka-do-klatki'), (SELECT id FROM muscle_groups WHERE name = 'Biceps'), 'secondary'),
    ((SELECT id FROM exercises WHERE slug = 'wioslowanie-siedzac-wyciag'), (SELECT id FROM muscle_groups WHERE name = 'Plecy'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'przysiad-ze-sztanga'), (SELECT id FROM muscle_groups WHERE name = 'Czworogłowe uda'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'przysiad-ze-sztanga'), (SELECT id FROM muscle_groups WHERE name = 'Pośladki'), 'secondary'),
    ((SELECT id FROM exercises WHERE slug = 'martwy-ciag-rumunski'), (SELECT id FROM muscle_groups WHERE name = 'Dwugłowe uda'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'martwy-ciag-rumunski'), (SELECT id FROM muscle_groups WHERE name = 'Pośladki'), 'secondary'),
    ((SELECT id FROM exercises WHERE slug = 'wypychanie-na-suwnicy'), (SELECT id FROM muscle_groups WHERE name = 'Czworogłowe uda'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'wypychanie-na-suwnicy'), (SELECT id FROM muscle_groups WHERE name = 'Pośladki'), 'secondary'),
    ((SELECT id FROM exercises WHERE slug = 'wykroki-z-hantlami'), (SELECT id FROM muscle_groups WHERE name = 'Czworogłowe uda'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'wykroki-z-hantlami'), (SELECT id FROM muscle_groups WHERE name = 'Pośladki'), 'secondary'),
    ((SELECT id FROM exercises WHERE slug = 'uginanie-nog-lezac'), (SELECT id FROM muscle_groups WHERE name = 'Dwugłowe uda'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'wspiecia-na-palce'), (SELECT id FROM muscle_groups WHERE name = 'Łydki'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'martwy-ciag-klasyczny'), (SELECT id FROM muscle_groups WHERE name = 'Plecy'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'martwy-ciag-klasyczny'), (SELECT id FROM muscle_groups WHERE name = 'Dwugłowe uda'), 'secondary'),
    ((SELECT id FROM exercises WHERE slug = 'martwy-ciag-klasyczny'), (SELECT id FROM muscle_groups WHERE name = 'Pośladki'), 'secondary'),
    ((SELECT id FROM exercises WHERE slug = 'hip-thrust'), (SELECT id FROM muscle_groups WHERE name = 'Pośladki'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'uginanie-ramion-z-hantlami'), (SELECT id FROM muscle_groups WHERE name = 'Biceps'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'uginanie-mlotkowe'), (SELECT id FROM muscle_groups WHERE name = 'Biceps'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'prostowanie-ramion-na-wyciagu'), (SELECT id FROM muscle_groups WHERE name = 'Triceps'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'francuskie-wyciskanie-lezac'), (SELECT id FROM muscle_groups WHERE name = 'Triceps'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'plank'), (SELECT id FROM muscle_groups WHERE name = 'Core'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'spiecia-brzucha-na-wyciagu'), (SELECT id FROM muscle_groups WHERE name = 'Core'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'face-pull'), (SELECT id FROM muscle_groups WHERE name = 'Barki'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'face-pull'), (SELECT id FROM muscle_groups WHERE name = 'Plecy'), 'secondary'),
    ((SELECT id FROM exercises WHERE slug = 'dipy-na-poreczach'), (SELECT id FROM muscle_groups WHERE name = 'Triceps'), 'primary'),
    ((SELECT id FROM exercises WHERE slug = 'dipy-na-poreczach'), (SELECT id FROM muscle_groups WHERE name = 'Klatka piersiowa'), 'secondary');

INSERT INTO workout_plans (owner_user_id, name, description, goal, level, is_template, is_public) VALUES
    (NULL, 'FBW 3 dni', 'Gotowy plan całego ciała wykonywany trzy razy w tygodniu.', 'general', 'beginner', TRUE, TRUE),
    (NULL, 'Push Pull Legs', 'Gotowy plan hipertroficzny z podziałem na wypychanie, przyciąganie i nogi.', 'hypertrophy', 'intermediate', TRUE, TRUE),
    ((SELECT id FROM users WHERE username = 'user'), 'Mój plan - hipertrofia', 'Własny plan użytkownika oparty o Push Pull Legs.', 'hypertrophy', 'intermediate', FALSE, FALSE);

INSERT INTO workout_plan_days (workout_plan_id, name, day_of_week, day_order, notes) VALUES
    ((SELECT id FROM workout_plans WHERE name = 'FBW 3 dni'), 'FBW A', 1, 1, 'Pierwszy trening tygodnia.'),
    ((SELECT id FROM workout_plans WHERE name = 'FBW 3 dni'), 'FBW B', 3, 2, 'Drugi trening tygodnia.'),
    ((SELECT id FROM workout_plans WHERE name = 'FBW 3 dni'), 'FBW C', 5, 3, 'Trzeci trening tygodnia.'),
    ((SELECT id FROM workout_plans WHERE name = 'Push Pull Legs'), 'Push', 1, 1, 'Klatka, barki i triceps.'),
    ((SELECT id FROM workout_plans WHERE name = 'Push Pull Legs'), 'Pull', 3, 2, 'Plecy i biceps.'),
    ((SELECT id FROM workout_plans WHERE name = 'Push Pull Legs'), 'Legs', 5, 3, 'Nogi i core.'),
    ((SELECT id FROM workout_plans WHERE name = 'Mój plan - hipertrofia'), 'Push A', 1, 1, 'Mocniejszy akcent na klatkę.'),
    ((SELECT id FROM workout_plans WHERE name = 'Mój plan - hipertrofia'), 'Pull A', 3, 2, 'Objętość na plecy.'),
    ((SELECT id FROM workout_plans WHERE name = 'Mój plan - hipertrofia'), 'Legs A', 5, 3, 'Przysiad i tył uda.');

INSERT INTO workout_plan_exercises (workout_plan_day_id, exercise_id, exercise_order, target_sets, target_reps_min, target_reps_max, target_rpe, rest_seconds, notes) VALUES
    ((SELECT id FROM workout_plan_days WHERE name = 'FBW A' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'FBW 3 dni')), (SELECT id FROM exercises WHERE slug = 'przysiad-ze-sztanga'), 1, 3, 6, 8, 8, 150, NULL),
    ((SELECT id FROM workout_plan_days WHERE name = 'FBW A' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'FBW 3 dni')), (SELECT id FROM exercises WHERE slug = 'wyciskanie-sztangi-lezac'), 2, 3, 8, 10, 8, 120, NULL),
    ((SELECT id FROM workout_plan_days WHERE name = 'FBW A' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'FBW 3 dni')), (SELECT id FROM exercises WHERE slug = 'wioslowanie-sztanga'), 3, 3, 8, 10, 8, 120, NULL),
    ((SELECT id FROM workout_plan_days WHERE name = 'FBW B' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'FBW 3 dni')), (SELECT id FROM exercises WHERE slug = 'martwy-ciag-rumunski'), 1, 3, 8, 10, 8, 150, NULL),
    ((SELECT id FROM workout_plan_days WHERE name = 'FBW B' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'FBW 3 dni')), (SELECT id FROM exercises WHERE slug = 'wyciskanie-zolnierskie'), 2, 3, 6, 8, 8, 120, NULL),
    ((SELECT id FROM workout_plan_days WHERE name = 'FBW B' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'FBW 3 dni')), (SELECT id FROM exercises WHERE slug = 'podciaganie-nachwytem'), 3, 3, 6, 10, 8, 120, NULL),
    ((SELECT id FROM workout_plan_days WHERE name = 'FBW C' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'FBW 3 dni')), (SELECT id FROM exercises WHERE slug = 'wypychanie-na-suwnicy'), 1, 3, 10, 12, 8, 120, NULL),
    ((SELECT id FROM workout_plan_days WHERE name = 'FBW C' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'FBW 3 dni')), (SELECT id FROM exercises WHERE slug = 'wyciskanie-hantli-skos-dodatni'), 2, 3, 8, 12, 8, 120, NULL),
    ((SELECT id FROM workout_plan_days WHERE name = 'FBW C' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'FBW 3 dni')), (SELECT id FROM exercises WHERE slug = 'sciaganie-drazka-do-klatki'), 3, 3, 10, 12, 8, 90, NULL),
    ((SELECT id FROM workout_plan_days WHERE name = 'Push' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'Push Pull Legs')), (SELECT id FROM exercises WHERE slug = 'wyciskanie-sztangi-lezac'), 1, 4, 6, 8, 8, 150, NULL),
    ((SELECT id FROM workout_plan_days WHERE name = 'Push' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'Push Pull Legs')), (SELECT id FROM exercises WHERE slug = 'wyciskanie-hantli-skos-dodatni'), 2, 3, 8, 10, 8, 120, NULL),
    ((SELECT id FROM workout_plan_days WHERE name = 'Push' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'Push Pull Legs')), (SELECT id FROM exercises WHERE slug = 'unoszenie-hantli-bokiem'), 3, 4, 12, 15, 8, 75, NULL),
    ((SELECT id FROM workout_plan_days WHERE name = 'Push' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'Push Pull Legs')), (SELECT id FROM exercises WHERE slug = 'prostowanie-ramion-na-wyciagu'), 4, 3, 10, 15, 8, 75, NULL),
    ((SELECT id FROM workout_plan_days WHERE name = 'Pull' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'Push Pull Legs')), (SELECT id FROM exercises WHERE slug = 'podciaganie-nachwytem'), 1, 4, 6, 10, 8, 150, NULL),
    ((SELECT id FROM workout_plan_days WHERE name = 'Pull' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'Push Pull Legs')), (SELECT id FROM exercises WHERE slug = 'wioslowanie-sztanga'), 2, 4, 8, 10, 8, 120, NULL),
    ((SELECT id FROM workout_plan_days WHERE name = 'Pull' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'Push Pull Legs')), (SELECT id FROM exercises WHERE slug = 'face-pull'), 3, 3, 12, 15, 7, 75, NULL),
    ((SELECT id FROM workout_plan_days WHERE name = 'Pull' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'Push Pull Legs')), (SELECT id FROM exercises WHERE slug = 'uginanie-ramion-z-hantlami'), 4, 3, 10, 12, 8, 75, NULL),
    ((SELECT id FROM workout_plan_days WHERE name = 'Legs' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'Push Pull Legs')), (SELECT id FROM exercises WHERE slug = 'przysiad-ze-sztanga'), 1, 4, 6, 8, 8, 150, NULL),
    ((SELECT id FROM workout_plan_days WHERE name = 'Legs' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'Push Pull Legs')), (SELECT id FROM exercises WHERE slug = 'martwy-ciag-rumunski'), 2, 3, 8, 10, 8, 120, NULL),
    ((SELECT id FROM workout_plan_days WHERE name = 'Legs' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'Push Pull Legs')), (SELECT id FROM exercises WHERE slug = 'wykroki-z-hantlami'), 3, 3, 10, 12, 8, 90, 'Na nogę.'),
    ((SELECT id FROM workout_plan_days WHERE name = 'Legs' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'Push Pull Legs')), (SELECT id FROM exercises WHERE slug = 'plank'), 4, 3, 30, 60, 7, 60, 'Czas w sekundach wpisywany w polu powtórzeń.');

INSERT INTO user_workout_plans (user_id, workout_plan_id, custom_name, is_active) VALUES
    ((SELECT id FROM users WHERE username = 'user'), (SELECT id FROM workout_plans WHERE name = 'Push Pull Legs'), 'PPL - aktualny plan', TRUE);

INSERT INTO badges (created_by_user_id, exercise_id, muscle_group_id, name, slug, description, icon, criteria_type, target_value, is_active) VALUES
    ((SELECT id FROM users WHERE username = 'admin'), (SELECT id FROM exercises WHERE slug = 'wyciskanie-sztangi-lezac'), NULL, 'Pierwsza stówka na klatę', 'pierwsza-stowka-na-klate', 'Przyznawana za wykonanie serii wyciskania sztangi leżąc z ciężarem co najmniej 100 kg.', 'workspace_premium', 'exercise_weight', 100, TRUE),
    ((SELECT id FROM users WHERE username = 'admin'), (SELECT id FROM exercises WHERE slug = 'przysiad-ze-sztanga'), NULL, 'Przysiad 120 kg', 'przysiad-120-kg', 'Przyznawana za wykonanie serii przysiadu ze sztangą z ciężarem co najmniej 120 kg.', 'military_tech', 'exercise_weight', 120, TRUE),
    ((SELECT id FROM users WHERE username = 'admin'), (SELECT id FROM exercises WHERE slug = 'martwy-ciag-klasyczny'), NULL, 'Martwy ciąg 150 kg', 'martwy-ciag-150-kg', 'Przyznawana za wykonanie serii martwego ciągu klasycznego z ciężarem co najmniej 150 kg.', 'trophy', 'exercise_weight', 150, TRUE),
    ((SELECT id FROM users WHERE username = 'admin'), NULL, NULL, 'Pierwszy trening', 'pierwszy-trening', 'Przyznawana za zakończenie pierwszej sesji treningowej.', 'flag', 'total_sessions', 1, TRUE),
    ((SELECT id FROM users WHERE username = 'admin'), NULL, NULL, '10 treningów', '10-treningow', 'Przyznawana za zakończenie 10 sesji treningowych.', 'event_available', 'total_sessions', 10, TRUE),
    ((SELECT id FROM users WHERE username = 'admin'), NULL, NULL, 'Objętość 10000 kg', 'objetosc-10000-kg', 'Przyznawana za uzbieranie 10000 kg całkowitej objętości.', 'monitoring', 'total_volume', 10000, TRUE),
    ((SELECT id FROM users WHERE username = 'admin'), NULL, (SELECT id FROM muscle_groups WHERE name = 'Plecy'), 'Plecy pod kontrolą', 'plecy-pod-kontrola', 'Przyznawana za wykonanie wyznaczonej liczby serii na plecy.', 'fitness_center', 'muscle_sets', 20, TRUE);

BEGIN;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

WITH created_session AS (
    INSERT INTO workout_sessions (
        user_id,
        workout_plan_id,
        workout_plan_day_id,
        name,
        status,
        started_at,
        finished_at,
        session_rpe,
        notes
    )
    VALUES (
        (SELECT id FROM users WHERE username = 'user'),
        (SELECT id FROM workout_plans WHERE name = 'Push Pull Legs'),
        (SELECT id FROM workout_plan_days WHERE name = 'Push' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'Push Pull Legs')),
        'Push - trening testowy',
        'finished',
        CURRENT_TIMESTAMP - INTERVAL '5 days',
        CURRENT_TIMESTAMP - INTERVAL '5 days' + INTERVAL '72 minutes',
        8.0,
        'Dobra energia, lekki zapas na wyciskaniu.'
    )
    RETURNING id
),
set_rows(exercise_slug, set_order, weight_kg, reps, rpe, note) AS (
    VALUES
        ('wyciskanie-sztangi-lezac', 1, 100.00, 1, 8.5, 'Pierwsza stówka na klatę.'),
        ('wyciskanie-sztangi-lezac', 2, 80.00, 8, 8.5, NULL),
        ('wyciskanie-sztangi-lezac', 3, 77.50, 8, 9.0, 'Ostatnia seria ciężka.'),
        ('wyciskanie-hantli-skos-dodatni', 1, 30.00, 10, 8.0, NULL),
        ('wyciskanie-hantli-skos-dodatni', 2, 30.00, 9, 8.5, NULL),
        ('unoszenie-hantli-bokiem', 1, 10.00, 15, 8.0, NULL),
        ('unoszenie-hantli-bokiem', 2, 10.00, 14, 8.0, NULL),
        ('prostowanie-ramion-na-wyciagu', 1, 35.00, 12, 8.0, NULL),
        ('prostowanie-ramion-na-wyciagu', 2, 35.00, 12, 8.0, NULL)
)
INSERT INTO performed_sets (workout_session_id, exercise_id, set_order, weight_kg, reps, rpe, note)
SELECT cs.id, e.id, sr.set_order, sr.weight_kg, sr.reps, sr.rpe, sr.note
FROM created_session cs
JOIN set_rows sr ON TRUE
JOIN exercises e ON e.slug = sr.exercise_slug;

WITH created_session AS (
    INSERT INTO workout_sessions (
        user_id,
        workout_plan_id,
        workout_plan_day_id,
        name,
        status,
        started_at,
        finished_at,
        session_rpe,
        notes
    )
    VALUES (
        (SELECT id FROM users WHERE username = 'user'),
        (SELECT id FROM workout_plans WHERE name = 'Push Pull Legs'),
        (SELECT id FROM workout_plan_days WHERE name = 'Pull' AND workout_plan_id = (SELECT id FROM workout_plans WHERE name = 'Push Pull Legs')),
        'Pull - trening testowy',
        'finished',
        CURRENT_TIMESTAMP - INTERVAL '2 days',
        CURRENT_TIMESTAMP - INTERVAL '2 days' + INTERVAL '65 minutes',
        7.5,
        'Podciąganie weszło lepiej niż tydzień temu.'
    )
    RETURNING id
),
set_rows(exercise_slug, set_order, weight_kg, reps, rpe, note) AS (
    VALUES
        ('podciaganie-nachwytem', 1, 0.00, 8, 8.0, NULL),
        ('podciaganie-nachwytem', 2, 0.00, 7, 8.5, NULL),
        ('podciaganie-nachwytem', 3, 0.00, 6, 9.0, NULL),
        ('wioslowanie-sztanga', 1, 70.00, 10, 8.0, NULL),
        ('wioslowanie-sztanga', 2, 70.00, 9, 8.0, NULL),
        ('face-pull', 1, 25.00, 15, 7.0, NULL),
        ('face-pull', 2, 25.00, 15, 7.5, NULL),
        ('uginanie-ramion-z-hantlami', 1, 14.00, 12, 8.0, NULL),
        ('uginanie-ramion-z-hantlami', 2, 14.00, 10, 8.5, NULL)
)
INSERT INTO performed_sets (workout_session_id, exercise_id, set_order, weight_kg, reps, rpe, note)
SELECT cs.id, e.id, sr.set_order, sr.weight_kg, sr.reps, sr.rpe, sr.note
FROM created_session cs
JOIN set_rows sr ON TRUE
JOIN exercises e ON e.slug = sr.exercise_slug;

COMMIT;
